<a href="https://colab.research.google.com/github/Micilvania/Python/blob/main/Mod_3_Aula_1_sabado20_8_22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Criando uma lista:

In [5]:
minhaLista = [0, 1, 2, 3, 4, 5, 6, 7, 8]
minhaLista

[0, 1, 2, 3, 4, 5, 6, 7, 8]

Transformando essa lista em um Array Numpy:

In [102]:
import numpy as np 
meuArray = np.array(minhaLista)
meuArray

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

Diferença entre array e print(array):

In [103]:
meuArray

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [9]:
print(meuArray)

[0 1 2 3 4 5 6 7 8]


Uma forma mais simples de criarmos essa lista:

In [71]:
minhaLista = list(range(9))

In [10]:
minhaLista

[0, 1, 2, 3, 4, 5, 6, 7, 8]

Transformando agora essa lista em um Array Numpy:

In [72]:
array1 = np.array(range(9))

In [73]:
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

Arange: Fazendo as etapas anteriores numa única sintaxe

In [75]:
array2 = np.arange(9)
array2

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

Start, stop, step:

In [76]:
array3 = np.arange(0, 10, 0.5)
array3

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

Arredondando os valores obtidos:

In [77]:
novoArray = np.around(array3)
novoArray

array([ 0.,  0.,  1.,  2.,  2.,  2.,  3.,  4.,  4.,  4.,  5.,  6.,  6.,
        6.,  7.,  8.,  8.,  8.,  9., 10.])

Também podemos “forçar” o tipo dos elementos:

In [78]:
array3 = np.arange(0, 10, 0.5, dtype=int)
array3

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Também podemos pré determinar o tipo dos elementos:

In [79]:
array4 = np.arange(12)

Acima teremos os números inteiros, mas posso deixar
meu array previamente preparado para trabalhar
futuramente com tipos float:

In [80]:
array4 = np.arange(12.)
array4

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

Verificando o tipo do objeto:

In [81]:
type(array4)

numpy.ndarray

Verificando o tipo dos elementos do array - #ou print(array4.dtype)

In [82]:
array4.dtype

dtype('float64')

Também podemos criar um array digitando os valores:

In [83]:
vetor1 = np.array([0, 1, 2, 3, 4])
print(vetor1)

[0 1 2 3 4]


Selecionando um elemento específico:

In [84]:
vetor1[3]

3

Selecionando um intervalo específico:

In [85]:
vetor1[0:2]
print(vetor1[0:2])

[0 1]


Criando um array de strings:

In [86]:
s = np.array(['Python', 'Profissional', 'Java', "Água"])
s

array(['Python', 'Profissional', 'Java', 'Água'], dtype='<U12')

In [87]:
s = np.array(['Python', 1464321315, 'Profissional', 'Java', "Água"])
s

array(['Python', '1464321315', 'Profissional', 'Java', 'Água'],
      dtype='<U21')

Alterando um elemento do Array:

In [88]:
vetor1[2] = 10
vetor1

array([ 0,  1, 10,  3,  4])

Vamos tentar incluir elementos:

In [109]:
vetor1[0] = 11
vetor1


array([11,  1, 10,  3,  4])

Agora tente o seguinte:

In [90]:
vetor1[0] = 45.6
vetor1

array([45,  1, 10,  3,  4])

Criando a primeira matriz:

In [91]:
minhaMatriz = np.array([[1,2,3],
                        [4, 5, 6]])

Lembrando que você pode escrever apenas assim:

In [92]:
minhaMatriz = np.array([[1,2,3], [4,5,6]])
minhaMatriz

array([[1, 2, 3],
       [4, 5, 6]])

Podemos criar uma matriz a partir de uma lista:

In [43]:
minhaLista = [[13,81,22], [0, 34, 59], [21, 48, 94]]

Agora usaremos np.matrix:

In [93]:
minhaMatriz = np.matrix(minhaLista)

np.zeros: pode formar vetores e matrizes - Vetor

In [94]:
x = np.zeros(3)
x

array([0., 0., 0.])

matriz


In [96]:
x = np.zeros((3,2)) 
x

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

np.zeros: pode formar vetores e matrizes - Vetor

In [47]:
print(np.zeros(3))

[0. 0. 0.]


Matriz

In [48]:
print(np.zeros((3, 2)))

[[0. 0.]
 [0. 0.]
 [0. 0.]]


np.ones:

In [49]:
x = np.ones((5,3))
x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

igualmente é possível para apenas um vetor:

In [50]:
y = np.ones(5)
y

array([1., 1., 1., 1., 1.])

np.diag para formar matrizes:

In [51]:
z = np.diag(np.array([1, 2, 3, 4, 5, 6]))
z

array([[1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 5, 0],
       [0, 0, 0, 0, 0, 6]])

np.eye para formar matrizes:

In [52]:
y = np.eye(5)
y

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

agora, determinando o tipo int:

In [53]:
y = np.eye(5, dtype= int)
y

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

Verificando o shape(forma) de duas maneiras:

In [54]:
np.shape(minhaMatriz)

(3, 3)

In [55]:
minhaMatriz.shape # ou

(3, 3)

Verificando o tipo da matriz:

In [56]:
type(minhaMatriz)

numpy.matrix

Verificando o tipo dos dados da matriz:

In [57]:
minhaMatriz.dtype

dtype('int64')

Selecionando elementos de uma matriz:

In [58]:
minhaMatriz[2, 1]

48

Selecionando a primeira linha da matriz:

In [59]:
print(minhaMatriz[0,:])

[[13 81 22]]


Selecionando a terceira coluna da matriz:

In [60]:
print(minhaMatriz[:,2])

[[22]
 [59]
 [94]]


Alterando um elemento da matriz:

In [61]:
minhaMatriz[1,0] = 100
minhaMatriz

matrix([[ 13,  81,  22],
        [100,  34,  59],
        [ 21,  48,  94]])

Obtendo a soma dos valores do array:

In [62]:
np.sum(meuArray)

36

Obtendo o produto:

In [63]:
np.prod(meuArray)

0

Obtendo a soma acumulada:

In [67]:
np.cumsum(meuArray)

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36])

Obtendo o valor mínimo do array:

In [111]:
y.min()

0

Obtendo o valor máximo:

In [112]:
y.max()

1

Obtendo a média dos valores do array:

In [98]:
np.mean(meuArray)

41.333333333333336

Obtendo a mediana:

In [99]:
np.median(meuArray)

34.0

Obtendo a variância dos valores:

In [100]:
np.var(meuArray)

895.1111111111111

Obtendo o desvio padrão dos valores:

In [101]:
np.std(meuArray)

29.91840756308917